### PR TITLE
OSX Development Note

### PR DESCRIPTION
**Pull request by adn5327**
A note was added to identify why this code will not compile on OSX. crypt.h does not exist on OSX.

### CODE REVIEW

**Comment by dpzmick** [comment]
This isn't 100% accurate. The struct doesn't exist because the crypt_r function doesn't exist on OS X.

Also, most of our assignments don't work on OS X.

Finally, these docs are about to change so I'm gonna hold off on merging this until we push the new versions though.

**Comment by adn5327** [comment]
Yeah, I know many of them don't run well on OSX, but I've noticed notes in Angrave's Wiki/ MP Docs when something explicitly doesn't work. 

Sounds good!

**Comment by dpzmick** [comment]
new page has been pushed, if you want this merged you should resolve the conflicts :)

**Comment by dpzmick** [comment]
lol

**Pull request closed without merging**
